package cz.portal.recenze;
import java.time.LocalDate;
import java.util.*;
import java.awt.Color;
import java.io.FileWriter;
import java.lang.reflect.Field;
import java.nio.file.Path;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import jctib.helper.clsHelper;
import jctib.helper.clsRegEx;


/**
 *
 * 
 */
public class frmMain extends javax.swing.JFrame 
{  
    
    
    
    public class clsTimerInputListener implements clsTimerInput.infTimerInputEventListener
    {
        /*
        časovač pro vstup přes schránku: běží cyklus, který monitoruje schránku, a když 
        se její obsah změní, použije její nový obsah jako určitou část dat. Prostě
        aby člověk nemusel pořád překlikávat z jednoho okna do druhého
        */
        private frmMain parent;
        public void init(frmMain _parent)
        {
            this.parent=_parent;
        }
        @Override public void input_received(clsTimerInput.clsInputEvent e)
        {
            clsHelper.print("Event fired! "+e.value);
            String s=e.value;
            if (s.startsWith("http://")||s.startsWith("https://"))
                parent.txtRURL.setText(s);
            else if (s.length()==1)
                parent.txtAutor.setText("?");
            else if (s.length()>500)
                parent.txpOrig.setText(s);
            else
            {
                String[] words=s.split(" ");
                boolean all_capitalized=true;
                for (String w:words)
                {
                    if (clsRegEx.matches(w, "^\\p{Lu}")==false)
                        all_capitalized=false;
                }
                if (all_capitalized==true && words.length<=3)
                    parent.txtAutor.setText(s);
                else
                    parent.txtTitle.setText(s);
            }
        }
    }
    
    clsTimerInputListener L=new clsTimerInputListener();
    
    public class clsBookSelectedListener implements clsReviewMaker.infDataChangedEventListener
    {
        private frmMain parent;
        public void init(frmMain _parent)
        {
            this.parent=_parent;
        }
        @Override public void book_selected(clsBook b)
        {
            this.parent.book_selected(b);
        }
        @Override public void source_selected(String s)
        {   
            this.parent.source_selected(s);
        }
    }
    clsBookSelectedListener Lbs=new clsBookSelectedListener();
    
    public frmMain() {
        initComponents();
        clsReviewMaker.add_listener(Lbs);
        lblFeed.setText(clsFeed.feed_status());
        if ("neexistuje".equals(lblFeed.getText()) || "-chyba-".equals(lblFeed.getText()))
            lblFeed.setForeground(Color.RED);
        else
            lblFeed.setForeground(Color.GREEN);
        
        L.init(this);
        Lbs.init(this);
        clsTimerInput.add_listener(this.L);
        clsReviewMaker.add_listener(this.Lbs);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmdDownload = new javax.swing.JButton();
        lblFeed = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        btnCheck = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpOrig = new javax.swing.JTextPane();
        btnAdapt = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnExport = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txpNew = new javax.swing.JTextPane();
        lblExport = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        btnTimerInput = new javax.swing.JButton();
        cmdClear = new javax.swing.JButton();
        txtBookProp = new javax.swing.JTextField();
        btnSelectBook = new javax.swing.JButton();
        cmdFromFile = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        txtAutor2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRURL = new javax.swing.JTextField();
        chbFor = new javax.swing.JCheckBox();
        txtFor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        lblSource = new javax.swing.JLabel();
        btnCancelSource = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("XML Feed"));

        cmdDownload.setText("Stáhnout");
        cmdDownload.setActionCommand("cmdDownload");
        cmdDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDownloadActionPerformed(evt);
            }
        });

        lblFeed.setText("XML feed: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFeed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdDownload)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFeed)
                    .addComponent(cmdDownload))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jSplitPane1.setDividerLocation(300);

        btnCheck.setText("Zkontrolovat na e-shopu");
        btnCheck.setToolTipText("Zkontroluje, zda se tato recenze už na e-shopu nenachází");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        txpOrig.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txpOrigKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txpOrig);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))
        );

        btnAdapt.setText(">>>");
        btnAdapt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdaptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(btnCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdapt)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheck)
                    .addComponent(btnAdapt))
                .addGap(3, 3, 3)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel2);

        btnExport.setText("Export");
        btnExport.setInheritsPopupMenu(true);
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(txpNew);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExport, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExport)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExport)
                    .addComponent(lblExport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel6);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Kniha"));

        btnTimerInput.setText("A");
        btnTimerInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimerInputActionPerformed(evt);
            }
        });

        cmdClear.setText("Vyčisti");
        cmdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClearActionPerformed(evt);
            }
        });

        txtBookProp.setEditable(false);

        btnSelectBook.setText("Vybrat knihu");
        btnSelectBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectBookActionPerformed(evt);
            }
        });

        cmdFromFile.setText("F");
        cmdFromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFromFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnSelectBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName)
                            .addComponent(txtBookProp, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnTimerInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdFromFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdClear)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectBook))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBookProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdClear)
                    .addComponent(btnTimerInput)
                    .addComponent(cmdFromFile))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Metadata recenze"));

        jLabel1.setText("Autor");

        jLabel2.setText("další ");
        jLabel2.setToolTipText("Další informace o autorovi (instituce atd)");

        jLabel3.setText("URL");

        chbFor.setText("Zpracováno pro:");

        jLabel4.setText("Titulek");

        lblSource.setText("Soubor:  ");

        btnCancelSource.setText("x");
        btnCancelSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelSourceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAutor2))
                            .addComponent(txtRURL)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(chbFor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFor))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblSource)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelSource)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTitle)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAutor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbFor)
                    .addComponent(txtFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSource)
                    .addComponent(btnCancelSource))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDownloadActionPerformed
        try
        {//stažení nové verze feedu
            clsFeed.download_feed();
        }catch(Exception e){}
    }//GEN-LAST:event_cmdDownloadActionPerformed

    private void btnTimerInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimerInputActionPerformed
        clsTimerInput.start();
    }//GEN-LAST:event_btnTimerInputActionPerformed

    private void cmdClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClearActionPerformed
     
        clear_form();
    }//GEN-LAST:event_cmdClearActionPerformed

    private String insert_tag(String str,String tag1,String tag2, int s, int e)
    {
        String S1=str.substring(0, s);
        String S2=str.substring(s,e);
        String S3=str.substring(e);
        
        String new_str=S1+tag1+S2+tag2+S3;
        
        return new_str;
    }
    private String insert_tag(String tag)
    {
        return insert_tag(txpOrig.getText(),tag,tag.replaceAll("<", "</"),txpOrig.getSelectionStart(),txpOrig.getSelectionEnd());
    }
    private String insert_tag_on_lines(String wrapping_tag,String single_line_tag)
    {
        String wrapping_tag_end=wrapping_tag.replaceAll("<", "</");
        String single_line_tag_end=single_line_tag.replaceAll("<", "</");
        String str=txpOrig.getText();
        int s=txpOrig.getSelectionStart();
        int e=txpOrig.getSelectionEnd();
        String S1=str.substring(0, s);
        String S2=str.substring(s,e);
        String S3=str.substring(e);
        
        String[] lines=S2.split("\n");
        S2="";
        for (String l:lines)
        {
            S2+=single_line_tag+l+single_line_tag_end+"\n";                    
        }
        
        S2="\n"+wrapping_tag+"\n"+S2+wrapping_tag_end+"\n";
        
        return S1+S2+S3;
    }
    private void txpOrigKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txpOrigKeyPressed
        // TODO add your handling code here:
        
        
        
        switch (evt.getKeyCode())
        {
            case 112:
                txpOrig.setText(this.insert_tag("<h4>"));
                break;
            case 113:
                txpOrig.setText(this.insert_tag("<strong>"));
                break;
            case 114:
                txpOrig.setText(this.insert_tag("<em>"));
                break;
            case 115:
                txpOrig.setText(this.insert_tag_on_lines("<ul>","<li>"));
                break;
        }
                
    }//GEN-LAST:event_txpOrigKeyPressed

    private void btnSelectBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectBookActionPerformed
        // TODO add your handling code here:
        frmSelectBook select = new frmSelectBook(this,true);
        select.parent=this;
        select.setVisible(true);
    }//GEN-LAST:event_btnSelectBookActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        clsReviewMaker.check_reviews(txpOrig.getText());
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnAdaptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdaptActionPerformed
        clsReviewMaker.check_reviews(txpOrig.getText());
        HashMap<String,String> reviewInfo=new HashMap<>();
        reviewInfo.put("autor", txtAutor.getText());
        reviewInfo.put("autor2", txtAutor2.getText());
        reviewInfo.put("url", txtRURL.getText());
        reviewInfo.put("titulek",txtTitle.getText());
        if (chbFor.isSelected())
            reviewInfo.put("pro", txtFor.getText());
        else
            reviewInfo.put("pro", "");
        clsReviewMaker.set_rev_info(reviewInfo);
        
        //vlastní vytvoření recenze
        txpNew.setText(clsReviewMaker.make_review(txpOrig.getText()));
    }//GEN-LAST:event_btnAdaptActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
       clsExport.export(txpNew.getText());
                
    }//GEN-LAST:event_btnExportActionPerformed

    private void cmdFromFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFromFileActionPerformed
        frmFileRenamer frmFR=new frmFileRenamer(this, true);
        frmFR.setVisible(true);
    }//GEN-LAST:event_cmdFromFileActionPerformed

    private void btnCancelSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelSourceActionPerformed
        clsReviewMaker.set_source("", "");
    }//GEN-LAST:event_btnCancelSourceActionPerformed
    private void clear_form()
    {
        Field[] fields=this.getClass().getDeclaredFields();
        for (Field f : fields)
        {
            try
            {
                String f_cls=f.getType().getTypeName();
                if ("javax.swing.JTextField".equals(f_cls) || "javax.swing.JTextPane".equals(f_cls) )
                {
                    
                    Object o= f.get(this);
                    if (o instanceof javax.swing.JTextField)
                        ((javax.swing.JTextField) o).setText("");
                    else if (o instanceof javax.swing.JTextPane)
                        ((javax.swing.JTextPane) o).setText("");
                    //f.set(this, "");
                }
            }catch(Exception e)
            {
                clsHelper.print(e.getMessage());
            }
            
        }
        clsReviewMaker.set_book(null);
        clsReviewMaker.set_source("", "");
        clsReviewMaker.set_rev_info(null);
    }
    
    public void book_selected(clsBook b)
    {/*
        vybraná kniha (v clsReviewMaker) se změnila
        */
        if (b==null)
        {
            txtBookProp.setText("");
            txtName.setText("");
        }
        else
        {
            txtBookProp.setText("ean: " +b.ean+ " kód: "+b.kod);
            txtName.setText(b.autor+": "+b.name);
        }
        
    }
     public void source_selected(String s)
    {/*
        vybraná kniha (v clsReviewMaker) se změnila
        */
        if (s.equals(""))
            s=" -- recenze nepochází ze souboru -- ";
        lblSource.setText("Soubor: "+s);
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdapt;
    private javax.swing.JButton btnCancelSource;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnSelectBook;
    private javax.swing.JButton btnTimerInput;
    private javax.swing.JCheckBox chbFor;
    private javax.swing.JButton cmdClear;
    private javax.swing.JButton cmdDownload;
    private javax.swing.JButton cmdFromFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblExport;
    private javax.swing.JLabel lblFeed;
    private javax.swing.JLabel lblSource;
    private javax.swing.JTextPane txpNew;
    private javax.swing.JTextPane txpOrig;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtAutor2;
    private javax.swing.JTextField txtBookProp;
    private javax.swing.JTextField txtFor;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRURL;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
