/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cz.portal.recenze;

import java.util.*;

import javax.swing.DefaultListModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;


/**
 *
 * @author jctibor
 */
public class frmSelectBook extends javax.swing.JDialog {
    DefaultListModel lstModel=new DefaultListModel();
    ArrayList<clsBook> books;
    
    public frmMain parent;
    /**
     * Creates new form frmSelectBook
     */
    
    public frmSelectBook(java.awt.Frame parent, boolean modal) {
        super(parent, modal);        
        initComponents();
        
        javax.swing.text.Document d=this.txt.getDocument();
        d.addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                txtChanged();
            }
            @Override
            public void removeUpdate(DocumentEvent de) {
                txtChanged();
            }
            @Override
            public void changedUpdate(DocumentEvent de) {
                txtChanged();
            }
            
        }
        
        
        );
        this.lst.setModel(this.lstModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst = new javax.swing.JList<>();
        cmd_cancel = new javax.swing.JButton();
        cmd_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });
        txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKeyPressed(evt);
            }
        });

        lst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstMouseClicked(evt);
            }
        });
        lst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lstKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(lst);

        cmd_cancel.setText("Storno");
        cmd_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_cancelActionPerformed(evt);
            }
        });

        cmd_ok.setText("Ok");
        cmd_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmd_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmd_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_cancel)
                    .addComponent(cmd_ok))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtChanged()
    {
        String t=txt.getText();
        this.lstModel.clear();
        if (t.length()>=3)
        {
            
            books=Recenze.feed.find_books(txt.getText());

            for (clsBook b : books)
            {
                this.lstModel.addElement(b.kod + ": " + b.name+" ("+b.autor+")");
            }
        }
    }
    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
        send_data();
    }//GEN-LAST:event_txtActionPerformed

    private void cmd_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_okActionPerformed
        // TODO add your handling code here:
        send_data();
    }//GEN-LAST:event_cmd_okActionPerformed

    private void cmd_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_cancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cmd_cancelActionPerformed

    private void lstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstKeyPressed
        if (evt.getKeyCode()==13)
            send_data();
    }//GEN-LAST:event_lstKeyPressed

    private void lstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==2)
            this.send_data();
    }//GEN-LAST:event_lstMouseClicked

    private void txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyPressed
        // TODO add your handling code here:
        if (evt.isControlDown()==true && evt.getKeyCode()==10)
        {
            if (this.lstModel.size()>0)
            {
                this.lst.setSelectedIndex(0);
                this.send_data();
            }
        }
    }//GEN-LAST:event_txtKeyPressed
    private void send_data()
    {
        int i=this.lst.getSelectedIndex();
        if (i==-1 && books.size()>0)
            i=0;
        if (i>-1)
        {
            clsReviewMaker.set_book(books.get(i));
            this.setVisible(false);
        }
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_cancel;
    private javax.swing.JButton cmd_ok;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lst;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}
